# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdda616a16561a6333dd55ffd768237277f24ebaacfa18ef8fc907078744768c3588907f280266084d55c059a42f6ecaecca2e8eb80bdd4c8942339177821454

test:
  secret_key_base: 7aff7d471e30a197a9b3b3f4ea5d8dfc0be2f8f7dfd712dfbf3c26e526fa68f5f263a08aeee9cfd2a7074034fd46e7fee7916f2a16b2f5cee4ebb271f95d53de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
